FROM rust:1.77-alpine AS build
RUN apk add --no-cache musl-dev
WORKDIR /app
COPY rust ./rust
WORKDIR /app/rust
ENV RUSTFLAGS="-C target-feature=+crt-static"
RUN cargo build --release

FROM scratch
COPY --from=build /app/rust/target/release/vdx /vdx_rust
ENTRYPOINT ["/vdx_rust"]
